import "~/styles/globals.css";
import { Providers } from "./providers";
import { auth } from "~/server/auth/index";
import { GeistSans } from "geist/font/sans";
import { type Metadata } from "next";
import { Toaster } from "~/components/ui/toaster"

//TODO: Update metadata with your app's information
export const metadata: Metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default async function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {

  // Get the session object from the server database
  const session = await auth();

  return (
    <Providers session={session}>
    <html lang="en" className={`${GeistSans.variable}`}>
      <body>
        <main>{children}</main>
        <Toaster />
      </body>
    </html>
    </Providers>
  );
}
